version: '3.1'
services:
  springcloud-config:
    image: 192.168.1.8:5000/springcloud-config:v0.0.1
    container_name: springcloud-config
    ports:
      - 8085:8085
networks:
  default:
    external:
      name: configfiles-net