server:
  port: 8084
spring:
  cloud:
    config:
      label: master
#      profie: dev
  profiles:
    active: dev #一定加上才能激活相应环境
  application:
    name: spring-test-item
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
#eureka client config
eureka:
  instance:
    prefer-ip-address: true
    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.1.8:8082/eureka/
---
#spring-cloud-config-client //idea中模块的配置文件
server:
  port: 8084
spring:
  profiles: test
  application:
    name: spring-test-item
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.8:8082/eureka/
---
server:
  port: 8084
spring:
  profiles: prod
  application:
    name: spring-test-item
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.8:8082/eureka/