server:
  port: 8084
spring:
  application:
    name: springItem

#eureka client config
eureka:
  instance:
    prefer-ip-address: true
    #  instanc中的配置是让该服务使用IP注册到注册中心，而不是hostname
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/

